<?php

return [

    'avatar_image' => [
        'free' => [
            [ 'id' => 1, 'title' => 'Title1', 'url' => null, ],
            [ 'id' => 2, 'title' => 'Title2', 'url' => null, ],
            [ 'id' => 3, 'title' => 'Title3', 'url' => null, ],
            [ 'id' => 4, 'title' => 'Title4', 'url' => null, ],
            [ 'id' => 5, 'title' => 'Title5', 'url' => null, ],
            [ 'id' => 6, 'title' => 'Title6', 'url' => null, ],
            [ 'id' => 7, 'title' => 'Title7', 'url' => null, ],
            [ 'id' => 8, 'title' => 'Title8', 'url' => null, ],
            [ 'id' => 9, 'title' => 'Title9', 'url' => null, ],
            [ 'id' => 10, 'title' => 'Title10', 'url' => null, ],
            [ 'id' => 11, 'title' => 'Title11', 'url' => null, ],
            [ 'id' => 12, 'title' => 'Title12', 'url' => null, ],
            [ 'id' => 13, 'title' => 'Title13', 'url' => null, ],
            [ 'id' => 14, 'title' => 'Title14', 'url' => null, ],
            [ 'id' => 15, 'title' => 'Title15', 'url' => null, ],
            [ 'id' => 16, 'title' => 'Title16', 'url' => null, ],
            [ 'id' => 17, 'title' => 'Title17', 'url' => null, ],
            [ 'id' => 18, 'title' => 'Title18', 'url' => null, ],
            [ 'id' => 19, 'title' => 'Title19', 'url' => null, ],
        ],
        'pay' => [
            [ 'id' => 20, 'title' => 'Title20', 'url' => null, ],
            [ 'id' => 21, 'title' => 'Title21', 'url' => null, ],
            [ 'id' => 22, 'title' => 'Title22', 'url' => null, ],
            [ 'id' => 23, 'title' => 'Title23', 'url' => null, ],
            [ 'id' => 24, 'title' => 'Title24', 'url' => null, ],
            [ 'id' => 25, 'title' => 'Title25', 'url' => null, ],
            [ 'id' => 26, 'title' => 'Title26', 'url' => null, ],
            [ 'id' => 27, 'title' => 'Title27', 'url' => null, ],
            [ 'id' => 28, 'title' => 'Title28', 'url' => null, ],
            [ 'id' => 29, 'title' => 'Title29', 'url' => null, ],
        ],
    ],
    'border_image' => [
        'free' => [
            [ 'id' => 1, 'title' => 'Title1', 'url' => null, ],
            [ 'id' => 2, 'title' => 'Title2', 'url' => null, ],
            [ 'id' => 3, 'title' => 'Title3', 'url' => null, ],
            [ 'id' => 4, 'title' => 'Title4', 'url' => null, ],
            [ 'id' => 5, 'title' => 'Title5', 'url' => null, ],
            [ 'id' => 6, 'title' => 'Title6', 'url' => null, ],
            [ 'id' => 7, 'title' => 'Title7', 'url' => null, ],
            [ 'id' => 8, 'title' => 'Title8', 'url' => null, ],
            [ 'id' => 9, 'title' => 'Title9', 'url' => null, ],
            [ 'id' => 10, 'title' => 'Title10', 'url' => null, ],
            [ 'id' => 11, 'title' => 'Title11', 'url' => null, ],
            [ 'id' => 12, 'title' => 'Title12', 'url' => null, ],
            [ 'id' => 13, 'title' => 'Title13', 'url' => null, ],
            [ 'id' => 14, 'title' => 'Title14', 'url' => null, ],
            [ 'id' => 15, 'title' => 'Title15', 'url' => null, ],
            [ 'id' => 16, 'title' => 'Title16', 'url' => null, ],
            [ 'id' => 17, 'title' => 'Title17', 'url' => null, ],
            [ 'id' => 18, 'title' => 'Title18', 'url' => null, ],
            [ 'id' => 19, 'title' => 'Title19', 'url' => null, ],
        ],
        'pay' => [
            [ 'id' => 20, 'title' => 'Title20', 'url' => null, ],
            [ 'id' => 21, 'title' => 'Title21', 'url' => null, ],
            [ 'id' => 22, 'title' => 'Title22', 'url' => null, ],
            [ 'id' => 23, 'title' => 'Title23', 'url' => null, ],
            [ 'id' => 24, 'title' => 'Title24', 'url' => null, ],
            [ 'id' => 25, 'title' => 'Title25', 'url' => null, ],
            [ 'id' => 26, 'title' => 'Title26', 'url' => null, ],
            [ 'id' => 27, 'title' => 'Title27', 'url' => null, ],
            [ 'id' => 28, 'title' => 'Title28', 'url' => null, ],
            [ 'id' => 29, 'title' => 'Title29', 'url' => null, ],
        ],
    ],
    'change_image' => [
        'free' => [
            [ 'id' => 1, 'title' => 'Title1', 'url' => null, ],
            [ 'id' => 2, 'title' => 'Title2', 'url' => null, ],
        ],
        'pay' => [
            [ 'id' => 3, 'title' => 'Title3', 'url' => null, ],
            [ 'id' => 4, 'title' => 'Title4', 'url' => null, ],
            [ 'id' => 5, 'title' => 'Title5', 'url' => null, ],
            [ 'id' => 6, 'title' => 'Title6', 'url' => null, ],
            [ 'id' => 7, 'title' => 'Title7', 'url' => null, ],
        ],
    ],
    'impact_image' => [
        'free' => [
            [ 'id' => 1, 'title' => 'Title1', 'url' => null, ],
            [ 'id' => 2, 'title' => 'Title2', 'url' => null, ],
        ],
        'pay' => [
            [ 'id' => 3, 'title' => 'Title3', 'url' => null, ],
            [ 'id' => 4, 'title' => 'Title4', 'url' => null, ],
            [ 'id' => 5, 'title' => 'Title5', 'url' => null, ],
            [ 'id' => 6, 'title' => 'Title6', 'url' => null, ],
            [ 'id' => 7, 'title' => 'Title7', 'url' => null, ],
        ],
    ],
    'victory_image' => [
        'free' => [
            [ 'id' => 1, 'title' => 'Title1', 'url' => null, ],
            [ 'id' => 2, 'title' => 'Title2', 'url' => null, ],
        ],
        'pay' => [
            [ 'id' => 3, 'title' => 'Title3', 'url' => null, ],
            [ 'id' => 4, 'title' => 'Title4', 'url' => null, ],
            [ 'id' => 5, 'title' => 'Title5', 'url' => null, ],
            [ 'id' => 6, 'title' => 'Title6', 'url' => null, ],
            [ 'id' => 7, 'title' => 'Title7', 'url' => null, ],
        ],
    ],

];
